### ISSUE TITLE
在服务器端使用报错

### ISSUE THREAD

**Issue by XIXaa** [ukmojb/EventTweaker#1]
[crash-2024-06-06_13.53.41-server.txt](https://github.com/user-attachments/files/15604510/crash-2024-06-06_13.53.41-server.txt)

**Comment by ukmojb** [comment]
> [crash-2024-06-06_13.53.41-server.txt](https://github.com/user-attachments/files/15604510/crash-2024-06-06_13.53.41-server.txt)

更新到1.2看看还有没有

**Comment by XIXaa** [comment]
有的

**Comment by ukmojb** [comment]
> 有的

新报告发一下

**Comment by XIXaa** [comment]
[crash-2024-06-06_14.18.15-server.txt](https://github.com/user-attachments/files/15604782/crash-2024-06-06_14.18.15-server.txt)

**Comment by ukmojb** [comment]
> [crash-2024-06-06_14.18.15-server.txt](https://github.com/user-attachments/files/15604782/crash-2024-06-06_14.18.15-server.txt)

有qq吗 加我3465854398

**Comment by ukmojb** [comment]
> [crash-2024-06-06_14.18.15-server.txt](https://github.com/user-attachments/files/15604782/crash-2024-06-06_14.18.15-server.txt)

[eventtweaker-1.2-fix.jar.zip](https://github.com/user-attachments/files/15605191/eventtweaker-1.2-fix.jar.zip)
没有的话试试这个

**Comment by XIXaa** [comment]
这个成功加载了
