### ISSUE TITLE
服务端使用报错

### ISSUE THREAD

**Issue by Googoo-INF** [ukmojb/EventTweaker#2]
我在使用了[#1](https://github.com/ukmojb/EventTweaker/issues/1)内的修复后依然崩溃
日志：
[crash-2024-06-22_18.07.32-server.txt](https://github.com/user-attachments/files/15936175/crash-2024-06-22_18.07.32-server.txt)

**Comment by ukmojb** [comment]
好了1.5把该去的去了，该加的也加了
